spring.application.name=phishing
spring.datasource.username=PHISHING_DB_OWNER
spring.datasource.password=1234
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.jpa.hibernate.ddl-auto=validate
